services:
  balance-management:
    build: ./AccountBalanceManagement
    image: lauralex/balance_management
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_balance_db:3306/balance_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
    depends_on:
      - mysql_balance_db
    restart: on-failure

  mysql_payment_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=payment_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_payment_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
  
  payment-management:
    build: ./PaymentManagement
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_payment_db:3306/payment_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
    depends_on:
      - mysql_payment_db
    restart: on-failure
    

  auth_management:
    build: ./AuthManagement
    ports:
      - "8085:8080"
    restart: on-failure

  mysql_friendship_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=friendship_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_friendship_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  
  friendship-management:
    build: ./FriendshipManagement
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_friendship_db:3306/friendship_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
    depends_on:
      - mysql_friendship_db
    restart: on-failure


  mysql_balance_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=balance_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_balance_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  user-management:
    build: ./UserManagement
    image: lauralex/user_management
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_user_db:3306/user_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
    depends_on:
      - mysql_user_db
    restart: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_user_db
    depends_on:
      - mysql_user_db
  
  mysql_user_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=user_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_user_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

volumes:
  mysql_user_data:
  mysql_balance_data:
  mysql_friendship_data:
  mysql_payment_data: