---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-management-config
data:
  server.address: "0.0.0.0"
  server.port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-management-app-deployment
spec:
  selector:
    matchLabels:
      app: balance-management-app
  template:
    metadata:
      labels:
        app: balance-management-app
    spec:
      containers:
      - name: balance-management-app
        image: lauralex/balance_management
        envFrom:
          - configMapRef:
              name: balance-management-config
        ports:
        - containerPort: 8080
---