---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-balance-config
data:
  MYSQL_DATABASE: "balance_management"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-balance-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "toor"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-management-config
data:
  spring.datasource.url: "jdbc:mysql://mysql-balance-service:3306/balance_management?serverTimezone=UTC"
  spring.datasource.username: "root"
  spring.datasource.password: "toor"
  server.address: "0.0.0.0"
  server.port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-balance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-balance
  template:
    metadata:
      labels:
        app: mysql-balance
    spec:
      containers:
      - name: mysql-balance
        image: mysql:8.0.33
        envFrom:
          - configMapRef:
              name: mysql-balance-config
          - secretRef:
              name: mysql-balance-secret
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-balance-service
spec:
  selector:
    app: mysql-balance
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-management-app-deployment
spec:
  selector:
    matchLabels:
      app: balance-management-app
  template:
    metadata:
      labels:
        app: balance-management-app
    spec:
      containers:
      - name: balance-management-app
        image: lauralex/balance_management
        envFrom:
          - configMapRef:
              name: balance-management-config
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-balance-deployment
  labels:
    app: adminer-balance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer-balance
  template:
    metadata:
      name: adminer-balance
      labels:
        app: adminer-balance
    spec:
      containers:
        - name: adminer-balance
          image: adminer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: mysql-balance-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-balance-service
spec:
  selector:
    app: adminer-balance
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: balance-management-app-service
spec:
  selector:
    app: balance-management-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---