---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-user-config
data:
  MYSQL_DATABASE: "user_management"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "toor"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
data:
  spring.datasource.url: "jdbc:mysql://mysql-user-service:3306/user_management?serverTimezone=UTC"
  spring.datasource.username: "root"
  spring.datasource.password: "toor"
  server.address: "0.0.0.0"
  server.port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
      - name: mysql-user
        image: mysql:8.0.33
        envFrom:
        - configMapRef:
            name: mysql-user-config
        - secretRef:
            name: mysql-user-secret
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-user-service
spec:
  selector:
    app: mysql-user
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-app-deployment
spec:
  selector:
    matchLabels:
      app: user-management-app
  template:
    metadata:
      labels:
        app: user-management-app
    spec:
      containers:
      - name: user-management-app
        image: lauralex/user_management
        envFrom:
          - configMapRef:
              name: user-management-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-app-service
spec:
  selector:
    app: user-management-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
